# Generated by Django 2.2 on 2022-01-30 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('batch_id', models.AutoField(primary_key=True, serialize=False)),
                ('batch_name', models.CharField(max_length=20)),
                ('batch_size', models.IntegerField()),
                ('class_start_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('trade_id', models.AutoField(primary_key=True, serialize=False)),
                ('trade_name', models.CharField(max_length=50)),
                ('trade_slug', models.SlugField(null=True, unique=True)),
                ('is_active', models.NullBooleanField(default=False)),
                ('is_delete', models.NullBooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingCenter',
            fields=[
                ('center_id', models.AutoField(primary_key=True, serialize=False)),
                ('center_name', models.CharField(max_length=100)),
                ('center_mobile_no', models.CharField(max_length=15)),
                ('center_mobile_no_2', models.CharField(blank=True, max_length=15, null=True)),
                ('center_email', models.EmailField(max_length=100)),
                ('center_address', models.CharField(max_length=250)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('district', models.CharField(max_length=30)),
                ('division', models.CharField(max_length=30)),
                ('thana', models.CharField(blank=True, max_length=30, null=True)),
                ('photo', models.FileField(blank=True, null=True, upload_to='documents/trining_center_image')),
                ('center_slug', models.SlugField(unique=True)),
                ('is_active', models.NullBooleanField(default=False)),
                ('is_delete', models.NullBooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TradeAssign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.NullBooleanField(default=True)),
                ('is_delete', models.NullBooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now_add=True, null=True)),
                ('assign_trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainingservice.Trade')),
                ('assign_training_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainingservice.TrainingCenter')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('session_id', models.AutoField(primary_key=True, serialize=False)),
                ('session_start_date', models.DateField()),
                ('session_end_date', models.DateField()),
                ('session_capacity', models.IntegerField(blank=True, null=True)),
                ('interview_date', models.DateField()),
                ('application_last_date', models.DateField()),
                ('interview_result_date', models.DateField()),
                ('is_active', models.NullBooleanField(default=True)),
                ('is_delete', models.NullBooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now_add=True, null=True)),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainingservice.Trade')),
            ],
        ),
    ]
