# Generated by Django 2.2 on 2022-01-29 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingCenter',
            fields=[
                ('center_id', models.AutoField(primary_key=True, serialize=False)),
                ('center_name', models.CharField(max_length=100)),
                ('center_mobile_no', models.CharField(max_length=15)),
                ('center_mobile_no_2', models.CharField(blank=True, max_length=15, null=True)),
                ('center_email', models.EmailField(max_length=100)),
                ('center_address', models.CharField(max_length=250)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('district', models.CharField(max_length=30)),
                ('division', models.CharField(max_length=30)),
                ('thana', models.CharField(blank=True, max_length=30, null=True)),
                ('photo', models.FileField(blank=True, null=True, upload_to='documents/trining_center_image')),
                ('center_slug', models.SlugField(unique=True)),
                ('is_active', models.NullBooleanField(default=False)),
                ('is_delete', models.NullBooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
