# Generated by Django 2.2 on 2022-01-30 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainingservice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='trade_assign',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to='trainingservice.TradeAssign'),
            preserve_default=False,
        ),
    ]
