# Generated by Django 2.2 on 2022-01-29 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainingservice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('trade_id', models.AutoField(primary_key=True, serialize=False)),
                ('trade_name', models.CharField(max_length=50)),
                ('trade_slug', models.SlugField(null=True, unique=True)),
            ],
        ),
    ]
