# Generated by Django 2.2 on 2022-01-30 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainingservice', '0002_batch_trade_assign'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='batch',
            name='is_active',
            field=models.NullBooleanField(default=True),
        ),
        migrations.AddField(
            model_name='batch',
            name='is_delete',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AddField(
            model_name='batch',
            name='modified',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
