# Generated by Django 2.2 on 2022-01-30 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=60)),
                ('student_fathers_name', models.CharField(max_length=50)),
                ('student_mothers_name', models.CharField(max_length=50)),
                ('student_date_of_birth', models.DateField(default=None)),
                ('student_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('student_passport_number', models.CharField(max_length=10)),
                ('student_mobile_no', models.CharField(blank=True, max_length=15, null=True)),
                ('student_image', models.FileField(blank=True, null=True, upload_to='documents/student_image')),
                ('student_slug', models.SlugField(unique=True)),
                ('is_active', models.NullBooleanField(default=False)),
                ('is_delete', models.NullBooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
