# Generated by Django 2.2 on 2022-01-30 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('others', 'Others')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='student_passport_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('education_id', models.AutoField(primary_key=True, serialize=False)),
                ('degree', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=50)),
                ('board', models.CharField(choices=[('dhaka', 'Dhaka'), ('cumilla', 'Cumilla'), ('barisal', 'Barisal'), ('chittagong', 'Chittagong'), ('dinajpur', 'Dinajpur'), ('jessore', 'Jessore'), ('rajshahi', 'Rajshahi'), ('mymensingh', 'Mymensingh'), ('sylhet', 'Sylhet'), ('madrasah', 'Madrasah'), ('technical', 'Technical'), ('university', 'University')], max_length=15)),
                ('institute', models.CharField(max_length=100)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student')),
            ],
        ),
    ]
