# Generated by Django 2.2 on 2022-01-30 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trainingservice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('batch_id', models.AutoField(primary_key=True, serialize=False)),
                ('batch_name', models.CharField(max_length=30)),
                ('batch_start_date', models.DateTimeField(blank=True, null=True)),
                ('class_time', models.TimeField(blank=True, null=True)),
                ('batch_slug', models.SlugField(unique=True)),
                ('is_active', models.NullBooleanField(default=True)),
                ('is_delete', models.NullBooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now_add=True, null=True)),
                ('ttc_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainingservice.TrainingCenter')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('country_id', models.AutoField(primary_key=True, serialize=False)),
                ('country_name', models.CharField(max_length=30)),
                ('country_flag', models.FileField(blank=True, null=True, upload_to='documents/country_image')),
                ('country_slug', models.SlugField(unique=True)),
                ('is_active', models.NullBooleanField(default=False)),
                ('is_delete', models.NullBooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=60)),
                ('student_fathers_name', models.CharField(max_length=50)),
                ('student_mothers_name', models.CharField(max_length=50)),
                ('student_date_of_birth', models.DateField(default=None)),
                ('student_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('student_passport_number', models.CharField(max_length=10)),
                ('student_mobile_no', models.CharField(blank=True, max_length=15, null=True)),
                ('student_image', models.FileField(blank=True, null=True, upload_to='documents/student_image')),
                ('student_slug', models.SlugField(unique=True)),
                ('is_active', models.NullBooleanField(default=False)),
                ('is_delete', models.NullBooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PDO',
            fields=[
                ('pdo_id', models.AutoField(primary_key=True, serialize=False)),
                ('pdo_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('selected', 'Selected'), ('po_approved', 'Principal Approved'), ('dg_approved', 'DG Approved'), ('completed', 'Completed')], default='Pending', max_length=30)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_active', models.NullBooleanField(default=False)),
                ('is_delete', models.NullBooleanField(default=False)),
                ('modified', models.DateTimeField(auto_now_add=True, null=True)),
                ('payment_status', models.BooleanField(default=False)),
                ('pdo_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdoservice.Batch')),
                ('pdo_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdoservice.Country')),
                ('pdo_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdoservice.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_id', models.CharField(max_length=200)),
                ('payment_amount', models.FloatField()),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('payment_pdo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdoservice.PDO')),
            ],
        ),
    ]
